import duckdb
#Counting Total Companies
duckdb.sql("SELECT COUNT(*), FROM '../data/companies_house.csv'").show()
#Finding how many different values CompanyStatus can be
duckdb.sql("SELECT  CompanyStatus, COUNT(*), FROM '../data/companies_house.csv' GROUP BY CompanyStatus").show()
#Counting Active IT Companies
duckdb.sql("""SELECT COUNT(*) FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Finding Active IT Companies
duckdb.sql("""SELECT CompanyName, "SICCode.SicText_1", "SICCode.SicText_2", "SICCode.SicText_3", "SICCode.SicText_4" FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%') LIMIT 5""").show()
#Finding Active IT Companies in Birmingham
duckdb.sql("""SELECT CompanyName, "RegAddress.PostCode" FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'B') AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Counting Active IT Companies in Birmingham
duckdb.sql("""SELECT COUNT(*) FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'B') AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Finding Active IT Companies in London
duckdb.sql("""SELECT CompanyName, "RegAddress.PostCode" FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND ((regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'E') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'EC') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'N') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'NW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SE') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'W') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'WC') ) AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Counting Active IT Companies in London
duckdb.sql("""SELECT COUNT(*) FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND ((regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'E') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'EC') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'N') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'NW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SE') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'W') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'WC') ) AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Finding Active IT Companies in both London and Birmingham
duckdb.sql("""SELECT CompanyName, "RegAddress.PostCode" FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND ((regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'B') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'E') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'EC') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'N') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'NW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SE') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'SW') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'W') OR (regexp_extract("RegAddress.PostCode", '^[A-Z]+') = 'WC') ) AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%')""").show()
#Counting Active IT Companies Without a postcode
duckdb.sql("""SELECT "RegAddress.PostCode", COUNT(*) FROM '../data/companies_house.csv' WHERE CompanyStatus = 'Active' AND (regexp_extract(CAST("SICCode.SicText_1" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_2" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_3" AS VARCHAR), '^[0-9]+') LIKE '62%' OR regexp_extract(CAST("SICCode.SicText_4" AS VARCHAR), '^[0-9]+') LIKE '62%') GROUP BY "RegAddress.PostCode" """).show()